AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Java Email Signup + Verification

Globals:
  Function:
    Runtime: java17
    Timeout: 10
    MemorySize: 512

Resources:
  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.company.signup.SignupHandler::handleRequest
      CodeUri: .
      Events:
        SignupAPI:
          Type: Api
          Properties:
            Path: /signup
            Method: post
      Environment:
        Variables:
          TABLE_NAME: user
          FROM_EMAIL: zeynalovkamran767@gmail.com
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSESFullAccess

  VerifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.company.verify.VerifyHandler::handleRequest
      CodeUri: .
      Events:
        VerifyAPI:
          Type: Api
          Properties:
            Path: /verify
            Method: get
      Environment:
        Variables:
          TABLE_NAME: user
      Policies:
        - AmazonDynamoDBFullAccess

  User:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: email
        Type: String
      TableName: user
